[tools]
chezmoi = "latest"
colima = "latest"
docker-cli = "latest"
docker-compose = "latest"
fzf = "latest"
gh = "latest"
herdr = "latest"
hunk = "latest"
lazygit = "latest"
lazydocker = "latest"
lima = "latest"
maestro = "latest"
pi = "latest"
starship = "latest"
superfile = "latest"
zoxide = "latest"
"github:sinelaw/fresh" = "latest"
