[tools]
chezmoi = "latest"
colima = "latest"
docker-cli = "latest"
docker-compose = "latest"
fzf = "latest"
gh = "latest"
herdr = "latest"
hunk = "latest"
lazygit = "latest"
lazydocker = "latest"
lima = "latest"
maestro = "latest"
pi = "latest"
starship = "latest"
superfile = "latest"
uv = "latest"
zoxide = "latest"
"github:loft-sh/devpod" = "0.6.15"
"github:sinelaw/fresh" = "0.5.1"
